services:
  frontend:
    build:
      context: .
      target: frontend-builder
    ports:
      - "3000:5173"
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
    command: npm run dev -w packages/frontend -- --host
    container_name: oomi-frontend
    networks:
      - oomi-network

  backend:
    build:
      context: .
      target: backend-builder
    ports:
      - "4000:4000"
    volumes:
      - ./packages/backend:/app/packages/backend
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/oomi
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev -w packages/backend
    container_name: oomi-backend
    networks:
      - oomi-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oomi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: oomi-db
    networks:
      - oomi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  oomi-network:
    driver: bridge

volumes:
  postgres_data: 