version: '3.8'

services:
  frontend:
    build:
      context: ./packages/frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:4000

  backend:
    build:
      context: ./packages/backend
      target: development
    ports:
      - "4000:4000"
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/oomi
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oomi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 