services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/frontend/node_modules
      - /app/packages/frontend/.turbo
      - /app/packages/frontend/dist
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c "cd packages/frontend && npm run dev -- --host"
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/oomi
      - JWT_SECRET=${JWT_SECRET}
    command: >
      sh -c "
        cd packages/backend &&
        npm install -g tsx &&
        npx prisma generate &&
        npx prisma db push --accept-data-loss &&
        npm run dev
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oomi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  prisma-studio:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/oomi
    command: >
      sh -c "
      cd packages/backend &&
      npx prisma migrate deploy &&
      npx prisma generate &&
      npx prisma studio --hostname 0.0.0.0 --port 5555 --browser none
      "
    depends_on:
      db:
        condition: service_healthy

  resume-parser:
    build:
      context: ./packages/resume-parser
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ENDPOINT_URL_S3=${AWS_ENDPOINT_URL_S3}
      - BUCKET_NAME=${BUCKET_NAME}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RUST_LOG=resume_parser=debug,info
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "test", "-f", "/app/config/default.yaml"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s  # Give RabbitMQ time to start up

volumes:
  postgres_data:
  resume_parser_target: