[package]
name = "resume-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async runtime
tokio = { version = "1.42", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Configuration
config = { version = "0.14", features = ["yaml"] }
dotenvy = "0.15"

# PDF processing
pdf-extract = "0.7"

# AWS S3 - Updated to latest stable versions
aws-config = "1.5.13"
aws-sdk-s3 = "1.68.0"
aws-sdk-sts = "1.54.0"
aws-types = "1.3.3"
aws-credential-types = "1.2.1"
aws-sdk-sso = "1.4.0"

# Database
sqlx = { version = "0.8.1", features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "uuid",
    "json"
] }

# Queue
lapin = "2.5"  # RabbitMQ client

# Utilities
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.11", features = ["v4", "serde"] }

# HTTP server
axum = { version = "0.7", features = ["multipart"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["cors"] }

# Testing
tempfile = "3.15"

# Entity extraction
regex = "1.11"
lazy_static = "1.5"

# Pin home crate to version compatible with Rust 1.77.0
home = "0.5.4"

[dev-dependencies]
reqwest = "0.11"
