[package]
name = "resume-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async runtime
tokio = { version = "1.36", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Configuration
config = "0.14"
dotenv = "0.15"

# PDF processing
lopdf = "0.31"
pdf-extract = "0.7"

# AWS S3
aws-config = "1.1"
aws-sdk-s3 = "1.16"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "json"] }

# Queue
lapin = "2.3"  # RabbitMQ client

# Utilities
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.7", features = ["v4", "serde"] }
