[package]
name = "resume-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async runtime
tokio = { version = "1.36", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Configuration
config = { version = "0.14", features = ["yaml"] }
dotenv = "0.15"

# PDF processing
pdf-extract = "0.7"

# AWS S3 - Updated to latest stable versions
aws-config = "1.1.1"
aws-sdk-s3 = "1.12.0"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "json"] }

# Queue
lapin = "2.3"  # RabbitMQ client

# Utilities
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.7", features = ["v4", "serde"] }

# HTTP server
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["trace"] }

# Testing
tempfile = "3.10"

# Entity extraction
regex = "1.10"
lazy_static = "1.4"