[package]
name = "resume-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async runtime
tokio = { version = "1.42", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Configuration
config = { version = "0.14", features = ["yaml"] }
dotenvy = "0.15"

# PDF processing
pdf-extract = "0.7"

# AWS S3
aws-config = "1.5.13"
aws-sdk-s3 = "1.68.0"
aws-sdk-sts = "1.54.0"
aws-types = "1.3.0"
aws-credential-types = "1.2.1"
aws-sdk-sso = "1.4.0"
aws-smithy-runtime-api = "1.1.0"

# Queue
lapin = "2.5"

# Metrics
prometheus = "0.13"
lazy_static = "1.4"

# Utilities
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.11", features = ["v4", "serde"] }
tempfile = "3.15"
regex = "1.11"
home = "0.5.4"

# Optional HTTP server dependencies
axum = { version = "0.7", optional = true }
tower-http = { version = "0.5", optional = true }

# Futures
futures-util = "0.3"
