name: Deploy to AWS

env:
  AWS_REGION: us-west-2
  ECS_CLUSTER: oomi-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Test AWS Connection
      run: |
        echo "Testing AWS Connection..."
        aws sts get-caller-identity
        
        echo "Creating ECS Cluster..."
        aws ecs create-cluster --cluster-name ${{ env.ECS_CLUSTER }} 