name: Deploy to AWS

env:
  AWS_REGION: us-west-2
  ECS_CLUSTER: oomi-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Test AWS Connection and Setup
      run: |
        echo "Testing AWS Connection..."
        aws sts get-caller-identity
        
        echo "Checking for existing cluster..."
        EXISTING_CLUSTER=$(aws ecs describe-clusters --clusters ${{ env.ECS_CLUSTER }} --query 'clusters[0].clusterName' --output text || echo "")
        
        if [ "$EXISTING_CLUSTER" == "None" ] || [ -z "$EXISTING_CLUSTER" ]; then
          echo "Creating new ECS cluster..."
          aws ecs create-cluster --cluster-name ${{ env.ECS_CLUSTER }}
        else
          echo "Cluster already exists"
        fi
